var _yt_www={};(function(g){var window=this;var baa,caa,Aa,Ea,ab,bb,kaa,fb,gb,laa,ob,maa,vb,Hb,Xb,cc,ec,Jc,xaa,yaa,waa,qd,zaa,Ad,Cd,Bd,Caa,Daa,Eaa,Faa,Jd,Ld,Md,Od,Qd,Haa,Ud,Gd,Rd,Td,Dd,Id,Nd,Kd,Vd,Jaa,he,ke,ne,pe,we,xe,Re,Se,Oaa,$e,af,Paa,df,hf,ff,ef,Qaa,lf,mf,pf,rf,sf,tf,wf,vf,yf,uf,zf,nf,qf,Waa,Af,Bf,Xaa,Yaa,Hf,Jf,Lf,Pf,Of,Qf,Sf,Zaa,$aa,aba,Tf,Uf,Zf,cg,dg,eg,hg,ig,jg,gba,hba,$f,bg,Yf,fba,ag,mg,ng,qa,aaa;g.ca=function(a){return function(){return g.aa[a].apply(this,arguments)}};
g.da=function(a){return void 0!==a};
g.l=function(a,b,c){a=a.split(".");c=c||g.ea;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&g.da(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};
g.m=function(a,b){for(var c=a.split("."),d=b||g.ea,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};
g.fa=function(){};
g.ga=function(a){a.getInstance=function(){return a.Dc?a.Dc:a.Dc=new a}};
g.ha=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};
g.ia=function(a){return"array"==g.ha(a)};
g.ka=function(a){var b=g.ha(a);return"array"==b||"object"==b&&"number"==typeof a.length};
g.ma=function(a){return"string"==typeof a};
g.na=function(a){return"number"==typeof a};
g.oa=function(a){return"function"==g.ha(a)};
g.pa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};
g.ra=function(a){return a[qa]||(a[qa]=++aaa)};
baa=function(a,b,c){return a.call.apply(a.bind,arguments)};
caa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};
g.p=function(a,b,c){g.p=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?baa:caa;return g.p.apply(null,arguments)};
g.sa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};
g.q=function(a,b){function c(){}
c.prototype=b.prototype;a.N=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,h){for(var k=Array(arguments.length-2),n=2;n<arguments.length;n++)k[n-2]=arguments[n];return b.prototype[c].apply(a,k)}};
g.ta=function(a){g.ta[" "](a);return a};
g.ua=function(a,b){return 0==a.lastIndexOf(b,0)};
g.va=function(a){return(0,window.encodeURIComponent)(String(a))};
g.wa=function(a){if(!daa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(eaa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(faa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gaa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(haa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(iaa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jaa,"&#0;"));return a};
g.xa=function(a,b){return-1!=a.indexOf(b)};
g.ya=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
g.Ca=function(a,b){for(var c=0,d=(0,g.za)(String(a)).split("."),e=(0,g.za)(String(b)).split("."),h=Math.max(d.length,e.length),k=0;0==c&&k<h;k++){var n=d[k]||"",r=e[k]||"",y=RegExp("(\\d*)(\\D*)","g"),C=RegExp("(\\d*)(\\D*)","g");do{var N=y.exec(n)||["","",""],ba=C.exec(r)||["","",""];if(0==N[0].length&&0==ba[0].length)break;c=Aa(0==N[1].length?0:(0,window.parseInt)(N[1],10),0==ba[1].length?0:(0,window.parseInt)(ba[1],10))||Aa(0==N[2].length,0==ba[2].length)||Aa(N[2],ba[2])}while(0==c)}return c};
Aa=function(a,b){return a<b?-1:a>b?1:0};
g.Da=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c)>>>0;return b};
Ea=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};
g.Fa=function(a){var b=g.ma(void 0)?g.ya(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};
g.Ha=function(a,b,c){b=g.Ga(a,b,c);return 0>b?null:g.ma(a)?a.charAt(b):a[b]};
g.Ga=function(a,b,c){for(var d=a.length,e=g.ma(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&b.call(c,e[h],h,a))return h;return-1};
g.Ka=function(a,b){return 0<=(0,g.Ja)(a,b)};
g.Ma=function(a,b){var c=(0,g.Ja)(a,b),d;(d=0<=c)&&g.La(a,c);return d};
g.La=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};
g.Na=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
g.Oa=function(a){return function(){return a}};
g.Pa=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};
g.Qa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};
g.Ra=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
g.Sa=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};
g.Ta=function(a,b){b in a&&delete a[b]};
g.Ua=function(a,b,c){if(null!==a&&b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};
g.Va=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
g.Xa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var h=0;h<Wa.length;h++)c=Wa[h],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
g.$a=function(a){return g.xa(g.Za,a)};
ab=function(){return g.$a("Opera")||g.$a("OPR")};
bb=function(){return(g.$a("Chrome")||g.$a("CriOS"))&&!ab()&&!g.$a("Edge")};
g.cb=function(a){g.ea.setTimeout(function(){throw a;},0)};
kaa=function(){var a=g.ea.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!g.$a("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,g.p)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);
b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});
if("undefined"!==typeof a&&!g.$a("Trident")&&!g.$a("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(g.da(c.next)){c=c.next;var a=c.Tp;c.Tp=null;a()}};
return function(a){d.next={Tp:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};
window.document.documentElement.appendChild(b)}:function(a){g.ea.setTimeout(a,0)}};
g.db=function(a,b,c){this.F=c;this.B=a;this.D=b;this.C=0;this.A=null};
g.eb=function(a,b){a.D(b);a.C<a.F&&(a.C++,b.next=a.A,a.A=b)};
fb=function(){this.C=this.A=null};
gb=function(){this.next=this.scope=this.Fe=null};
g.nb=function(a,b){ib||laa();jb||(ib(),jb=!0);var c=kb,d=lb.get();d.set(a,b);c.C?c.C.next=d:c.A=d;c.C=d};
laa=function(){if(g.ea.Promise&&g.ea.Promise.resolve){var a=g.ea.Promise.resolve(void 0);ib=function(){a.then(ob)}}else ib=function(){var a=ob;
!g.oa(g.ea.setImmediate)||g.ea.Window&&g.ea.Window.prototype&&!g.$a("Edge")&&g.ea.Window.prototype.setImmediate==g.ea.setImmediate?(pb||(pb=kaa()),pb(a)):g.ea.setImmediate(a)}};
ob=function(){for(var a=null;a=kb.remove();){try{a.Fe.call(a.scope)}catch(b){g.cb(b)}g.eb(lb,a)}jb=!1};
g.qb=function(){this.Hd=this.Hd;this.Ib=this.Ib};
g.tb=function(a,b){g.rb(a,g.sa(g.sb,b))};
g.rb=function(a,b){a.Hd?b.call(void 0):(a.Ib||(a.Ib=[]),a.Ib.push(g.da(void 0)?(0,g.p)(b,void 0):b))};
g.sb=function(a){a&&"function"==typeof a.dispose&&a.dispose()};
g.ub=function(a){g.qb.call(this);this.D=1;this.C=[];this.B=0;this.A=[];this.Fd={};this.F=!!a};
maa=function(a,b,c){g.nb(function(){a.apply(b,c)})};
g.xb=function(a){vb(g.wb,arguments)};
g.t=function(a,b){return a in g.wb?g.wb[a]:b};
g.zb=function(a,b){g.oa(a)&&(a=g.yb(a));return window.setTimeout(a,b)};
g.Ab=function(a,b){g.oa(a)&&(a=g.yb(a));return window.setInterval(a,b)};
g.Bb=function(a){window.clearTimeout(a)};
g.Cb=function(a){window.clearInterval(a)};
g.yb=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw g.Db(b),b;}}:a};
g.Db=function(a,b){var c=g.m("yt.logging.errors.log");c?c(a,b,void 0,void 0):(c=g.t("ERRORS",[]),c.push([a,b,void 0,void 0]),g.xb("ERRORS",c))};
g.Fb=function(a){return a in g.Eb};
g.Gb=function(a,b,c){var d=b||{};if(a=a in g.Eb?g.Eb[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});
return a};
vb=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
g.Mb=function(a,b,c){var d=Hb();if(d){var e=d.subscribe(a,function(){if(!Ib||Ib!=e){var d=arguments,k;k=function(){Jb[e]&&b.apply(c||window,d)};
try{Kb[a]?k():g.zb(k,0)}catch(n){g.Db(n)}}},c);
Jb[e]=!0;Lb[a]||(Lb[a]=[]);Lb[a].push(e);return e}return 0};
g.Nb=function(a){var b=Hb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,g.u)(a,function(a){b.unsubscribeByKey(a);delete Jb[a]}))};
g.v=function(a,b){var c=Hb();return c?c.publish.apply(c,arguments):!1};
g.Ob=function(a,b){Kb[a]=!0;var c=Hb(),c=c?c.publish.apply(c,arguments):!1;Kb[a]=!1;return c};
Hb=function(){return g.m("yt.pubsub.instance_")};
g.Pb=function(){return!!g.m("yt.scheduler.instance")};
g.Qb=function(a,b){(0,window.isNaN)(b)&&(b=void 0);var c=g.m("yt.scheduler.instance.addJob");return c?c(a,0,b):void 0===b?(a(),window.NaN):g.zb(a,b||0)};
g.Rb=function(a,b){return g.Qb(a,b)};
g.Sb=function(a){if(!(0,window.isNaN)(a)){var b=g.m("yt.scheduler.instance.cancelJob");b?b(a):g.Bb(a)}};
g.Tb=function(a){for(var b=0,c=a.length;b<c;b++)g.Sb(a[b])};
g.Ub=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.G=d?g.yb(d):null;this.F=e?g.yb(e):null;this.D=[];this.A=this.C=0};
g.Vb=function(a){g.Sb(a.C);a.C=g.Rb((0,g.p)(a.init,a))};
g.Yb=function(a){a.name in Wb&&Xb(a.name);Wb[a.name]={reqs:[],disable:(0,g.p)(a.disable,a)};(0,g.u)(a.deps,function(b){if(!(b in Wb))throw Error("Module "+b+" required by "+a.name);Wb[b].reqs.push(a.name)});
a.enable()};
Xb=function(a){if(a in Wb){var b=Wb[a];(0,g.u)(b.reqs,function(a){Xb(a)});
try{b.disable()}catch(c){}delete Wb[a]}};
g.$b=function(){this.A="";this.C=Zb};
g.ac=function(a){return a instanceof g.$b&&a.constructor===g.$b&&a.C===Zb?a.A:"type_error:Const"};
cc=function(){this.A="";this.C=bc};
g.dc=function(a){if(a instanceof cc&&a.constructor===cc&&a.C===bc)return a.A;g.ha(a);return"type_error:SafeStyle"};
ec=function(a){var b=new cc;b.A=a;return b};
g.fc=function(a){var b="",c;for(c in a){if(!/^[-_a-zA-Z0-9]+$/.test(c))throw Error("Name allows only [-_a-zA-Z0-9], got: "+c);var d=a[c];if(null!=d){if(d instanceof g.$b)d=g.ac(d);else if(naa.test(d)){for(var e=!0,h=!0,k=0;k<d.length;k++){var n=d.charAt(k);"'"==n&&h?e=!e:'"'==n&&e&&(h=!h)}e&&h||(d="zClosurez")}else d="zClosurez";b+=c+":"+d+";"}}return b?ec(b):oaa};
g.hc=function(){this.A="";this.C=gc};
g.ic=function(a){if(a instanceof g.hc&&a.constructor===g.hc&&a.C===gc)return a.A;g.ha(a);return"type_error:SafeUrl"};
g.kc=function(a){if(a instanceof g.hc)return a;a=a.Zf?a.af():String(a);paa.test(a)||(a="about:invalid#zClosurez");return g.jc(a)};
g.jc=function(a){var b=new g.hc;b.A=a;return b};
g.mc=function(){this.A="";this.C=lc};
g.nc=function(a){if(a instanceof g.mc&&a.constructor===g.mc&&a.C===lc)return a.A;g.ha(a);return"type_error:TrustedResourceUrl"};
g.pc=function(){this.A="";this.B=oc;this.C=null};
g.qc=function(a){if(a instanceof g.pc&&a.constructor===g.pc&&a.B===oc)return a.A;g.ha(a);return"type_error:SafeHtml"};
g.tc=function(a){if(a instanceof g.pc)return a;var b=null;a.Rm&&(b=a.Hg());a=g.wa(a.Zf?a.af():String(a));return g.sc(a,b)};
g.wc=function(a,b,c){if(!uc.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toUpperCase()in qaa)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");return g.vc(a,b,c)};
g.xc=function(a){function b(a){g.ia(a)?(0,g.u)(a,b):(a=g.tc(a),d+=g.qc(a),a=a.Hg(),0==c?c=a:0!=a&&c!=a&&(c=null))}
var c=0,d="";(0,g.u)(arguments,b);return g.sc(d,c)};
g.sc=function(a,b){var c=new g.pc;c.A=a;c.C=b;return c};
g.vc=function(a,b,c){var d=null,e,h="";if(b)for(e in b){if(!uc.test(e))throw Error('Invalid attribute name "'+e+'".');var k=b[e];if(null!=k){var n,r=a;n=e;if(k instanceof g.$b)k=g.ac(k);else if("style"==n.toLowerCase()){if(!g.pa(k))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof k+" given: "+k);k instanceof cc||(k=g.fc(k));k=g.dc(k)}else{if(/^on/i.test(n))throw Error('Attribute "'+n+'" requires goog.string.Const value, "'+k+'" given.');if(n.toLowerCase()in
raa)if(k instanceof g.mc)k=g.nc(k);else if(k instanceof g.hc)k=g.ic(k);else if(g.ma(k))k=g.kc(k).af();else throw Error('Attribute "'+n+'" on tag "'+r+'" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+k+'" given.');}k.Zf&&(k=k.af());n=n+'="'+g.wa(String(k))+'"';h+=" "+n}}e="<"+a+h;null!=c?g.ia(c)||(c=[c]):c=[];!0===saa[a.toLowerCase()]?e+=">":(d=g.xc(c),e+=">"+g.qc(d)+"</"+a+">",d=d.Hg());(a=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(a)?d=0:d=null);return g.sc(e,d)};
g.yc=function(a,b){a.innerHTML=g.qc(b)};
g.zc=function(a,b){var c;c=b instanceof g.hc?b:g.kc(b);a.href=g.ic(c)};
g.w=function(a,b){return a?a.dataset?a.dataset[g.Ac(b)]:a.getAttribute("data-"+b):null};
g.Bc=function(a,b){return a?a.dataset?g.Ac(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};
g.Ac=function(a){return Cc[a]||(Cc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};
g.Ec=function(a,b){var c=g.Dc(a);window.spf.script.load(a,c,b)};
g.Fc=function(a,b){var c=g.Dc(a);window.spf.script.ignore(c,b)};
g.Dc=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(taa,""),b=b.replace(uaa,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};
g.Gc=function(a,b){this.x=g.da(a)?a:0;this.y=g.da(b)?b:0};
g.Hc=function(a,b){this.width=a;this.height=b};
g.Ic=function(){return g.$a("iPhone")&&!g.$a("iPod")&&!g.$a("iPad")};
Jc=function(){var a=g.ea.document;return a?a.documentMode:void 0};
g.Nc=function(a){return Kc[a]||(Kc[a]=0<=g.Ca(g.Lc,a))};
g.Pc=function(a){return Number(g.Oc)>=a};
g.x=function(a){return g.ma(a)?window.document.getElementById(a):a};
g.Qc=function(a){return g.ma(a)?window.document.getElementById(a):a};
g.z=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=g.Rc(window.document,"*",a,b)[0];return d||null};
g.Rc=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,h=0,k;k=a[h];h++)b==k.nodeName&&(d[e++]=k);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(h=e=0;k=a[h];h++)b=k.className,"function"==typeof b.split&&g.Ka(b.split(/\s+/),c)&&(d[e++]=k);d.length=e;return d}return a};
g.Tc=function(a,b){g.Qa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Sc.hasOwnProperty(d)?a.setAttribute(Sc[d],b):g.ua(d,"aria-")||g.ua(d,"data-")?a.setAttribute(d,b):a[d]=b})};
g.Vc=function(a){return g.Uc(a||window)};
g.Uc=function(a){a=a.document;a=g.Wc(a)?a.documentElement:a.body;return new g.Hc(a.clientWidth,a.clientHeight)};
g.Yc=function(a){var b=g.Xc(a);a=a.parentWindow||a.defaultView;return g.A&&g.Nc("10")&&a.pageYOffset!=b.scrollTop?new g.Gc(b.scrollLeft,b.scrollTop):new g.Gc(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
g.Xc=function(a){return a.scrollingElement?a.scrollingElement:!g.Zc&&g.Wc(a)?a.documentElement:a.body||a.documentElement};
g.ad=function(a,b,c){return g.$c(window.document,arguments)};
g.$c=function(a,b){var c=b[0],d=b[1];if(!vaa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',g.wa(d.name),'"');if(d.type){c.push(' type="',g.wa(d.type),'"');var e={};g.Xa(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(g.ma(d)?c.className=d:g.ia(d)?c.className=d.join(" "):g.Tc(c,d));2<b.length&&g.bd(a,c,b,2);return c};
g.bd=function(a,b,c,d){function e(c){c&&b.appendChild(g.ma(c)?a.createTextNode(c):c)}
for(;d<c.length;d++){var h=c[d];!g.ka(h)||g.pa(h)&&0<h.nodeType?e(h):(0,g.u)(waa(h)?g.Na(h):h,e)}};
g.Wc=function(a){return"CSS1Compat"==a.compatMode};
g.cd=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};
g.dd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};
g.ed=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
xaa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
yaa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
g.fd=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
waa=function(a){if(a&&"number"==typeof a.length){if(g.pa(a))return"function"==typeof a.item||"string"==typeof a.item;if(g.oa(a))return"function"==typeof a.item}return!1};
g.gd=function(a,b,c,d){c||(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null};
g.hd=function(a,b,c,d,e,h,k){var n="";a&&(n+=a+":");c&&(n+="//",b&&(n+=b+"@"),n+=c,d&&(n+=":"+d));e&&(n+=e);h&&(n+="?"+h);k&&(n+="#"+k);return n};
g.id=function(a){return a?(0,window.decodeURI)(a):a};
g.kd=function(a,b){return b.match(g.jd)[a]||null};
g.ld=function(a){return g.id(g.kd(3,a))};
g.md=function(a){a=a.match(g.jd);return g.hd(null,null,null,null,a[5],a[6],a[7])};
g.nd=function(a){var b=a.indexOf("#");return 0>b?a:a.substr(0,b)};
g.od=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
g.pd=function(a,b,c){if(g.ia(b))for(var d=0;d<b.length;d++)g.pd(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",g.va(b))};
qd=function(a,b){for(var c in b)g.pd(c,b[c],a);return a};
g.rd=function(a){a=qd([],a);a[0]="";return a.join("")};
g.sd=function(a,b){return g.od(qd([a],b))};
g.td=function(a,b,c){a&&(c&&(c=g.Za,c=!(c&&0<=c.toLowerCase().indexOf("cobalt"))),c?a&&(a=g.ad("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),g.fd(a).body.appendChild(a)):zaa(a,b))};
g.ud=function(a){try{window.navigator&&window.navigator.sendBeacon&&window.navigator.sendBeacon(a,"")||g.td(a,void 0)}catch(b){g.td(a,void 0)}};
zaa=function(a,b){var c=new window.Image,d=""+Aaa++;vd[d]=c;c.onload=c.onerror=function(){b&&vd[d]&&b();delete vd[d]};
c.src=a};
g.wd=function(a,b){this.version=a;this.args=b};
g.xd=function(a,b){this.topic=a;this.Hf=b};
g.zd=function(a,b){var c=g.yd();return c?c.publish.call(c,a.toString(),a,b):!1};
g.yd=function(){return g.m("yt.pubsub2.instance_")};
Ad=function(a){g.wd.call(this,1,arguments)};
Cd=function(a){var b=a||window;if(!(b.performance&&b.performance.timing&&b.performance.getEntriesByType))return{Vk:0,ww:0};a=g.Vc(b);for(var c=[],d=b.document.getElementsByTagName("*"),e=0,h=d.length;e<h;e++){var k=d[e];if("IMG"==k.tagName||"IFRAME"==k.tagName){var n=Bd(k,k.src,a);if(n){if("IFRAME"==k.tagName){var r;try{r=Cd(k.contentWindow).Vk}catch(y){r=0}0<r&&(n.timing=r)}c.push(n)}}(n=b.getComputedStyle(k)["background-image"])&&(n=Baa.exec(n))&&1<n.length&&(n=Bd(k,n[1],a))&&c.push(n)}r=b.performance.getEntriesByType("resource");
k=b.performance.getEntriesByType("mark");d={};e=0;for(h=r.length;e<h;e++)n=r[e],d[n.name]=n.responseEnd;e=0;for(h=k.length;e<h;e++)n=k[e],"mark_iframe_loaded: "==n.name.slice(0,20)&&(d[n.name.slice(20)]=n.startTime);e=0;for(h=c.length;e<h;e++)k=c[e],k.timing||(k.timing=d[k.url]||0);b=Caa(b,r);a=Daa(b,a,c);k=c=0;if(a.length)for(d=r=0,e=a.length;d<e;d++)h=a[d],k=h.timing-k,0<k&&1>r&&(c+=(1-r)*k),k=h.timing,r=h.progress;return{Vk:Math.round(c||b),ww:k}};
Bd=function(a,b,c){if(b&&a.getBoundingClientRect){var d=a.getBoundingClientRect();a=Math.max(d.top,0);var e=Math.min(d.right,c.width);c=Math.min(d.bottom,c.height);d=Math.max(d.left,0);if(c>a&&e>d)return new Eaa(a,e,c,d,b)}return null};
Caa=function(a,b){var c,d=a.performance.timing.navigationStart;if("msFirstPaint"in a.performance.timing)c=a.performance.timing.A-d;else if("chrome"in a&&"loadTimes"in a.chrome){var e=a.chrome.loadTimes(),h=e.firstPaintTime;if(0<h){var k=e.startLoadTime;"requestTime"in e&&(k=e.requestTime);h>=k&&(c=1E3*(h-k))}}if(void 0===c||0>c||12E4<c){c=a.performance.timing.responseStart-d;for(var n={},d=a.document.getElementsByTagName("head")[0].children,e=0,h=d.length;e<h;e++)k=d[e],"SCRIPT"==k.tagName&&k.src&&
!k.async?n[k.src]=!0:"LINK"==k.tagName&&"stylesheet"==k.rel&&k.href&&(n[k.href]=!0);b.some(function(a){if(!n[a.name]||"script"!=a.initiatorType&&"link"!=a.initiatorType)return!0;a=a.responseEnd;if(void 0===c||a>c)c=a})}return Math.max(c,0)||0};
Daa=function(a,b,c){for(var d={0:0},e=0,h=0,k=c.length;h<k;h++){var n=c[h],r=a;n.timing>a&&(r=n.timing);d[r]||(d[r]=0);n=(n.A-n.D)*(n.B-n.C);d[r]+=n;e+=n}h=b.width*b.height;0<h&&(h=.1*Math.max(h-e,0),a in d||(d[a]=0),d[a]+=h,e+=h);a=[];if(e){for(var y in d)b=new Faa((0,window.parseFloat)(y),d[y]),a.push(b);a.sort(function(a,b){return a.timing-b.timing});
h=d=0;for(k=a.length;h<k;h++)b=a[h],d+=b.area,b.progress=d/e}return a};
Eaa=function(a,b,c,d,e){this.A=c;this.C=d;this.B=b;this.D=a;this.url=e};
Faa=function(a,b){this.area=b;this.timing=a};
g.Hd=function(a,b,c){Dd(c)[a]=b||Ed();b||Fd(a);Gd(!1,c)};
Jd=function(a,b){Id(void 0).yt_sts=a;g.Hd("_start",b,void 0)};
Ld=function(a){Kd(a);Gaa();g.l("yt.timing.pingSent_",!1,void 0)};
Md=function(a){a=Dd(a);if(a.aft)return a.aft;for(var b=g.t("TIMING_AFT_KEYS",["ol"]),c=b.length,d=0;d<c;d++){var e=a[b[d]];if(e)return e}return window.NaN};
Od=function(a,b){var c=b||Nd(void 0).span,d;d=a.redirectEnd-a.redirectStart;0<d&&(c.rtime_=d);d=a.domainLookupEnd-a.domainLookupStart;0<d&&(c.dns_=d);d=a.connectEnd-a.connectStart;0<d&&(c.tcp_=d);d=a.connectEnd-a.secureConnectionStart;a.secureConnectionStart>=a.navigationStart&&0<d&&(c.stcp_=d);d=a.responseStart-a.requestStart;0<d&&(c.req_=d);d=a.responseEnd-a.responseStart;0<d&&(c.rcv_=d)};
Qd=function(a){return Math.round(Pd.timing.navigationStart+a)};
Haa=function(a){var b=window.location.protocol,c=Pd.getEntriesByType("resource"),d=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.googleapis.com/css?family=")})[0],c=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});
d&&0<d.startTime&&0<d.responseEnd&&(a.wfcs=Qd(d.startTime),a.wfce=Qd(d.responseEnd));c&&0<c.startTime&&0<c.responseEnd&&(a.wffs=Qd(c.startTime),a.wffe=Qd(c.responseEnd))};
Ud=function(a){var b=Dd(a),c=Nd(a).span,d=Id(a),e=g.m("yt.timing.reportbuilder_");if(e){if(e=e(b,c,d,a))Rd(e),Ld(a)}else{var h=g.t("TIMING_ACTION",void 0),k=g.t("CSI_SERVICE_NAME","youtube"),e={v:2,s:k,action:h};if(Pd.now&&Pd.timing){var n=Pd.timing.navigationStart+Pd.now(),n=Math.round((0,g.Sd)()-n);d.yt_hrd=n}var n=g.t("TIMING_INFO",{}),r;for(r in n)d[r]=n[r];r=d.srt;delete d.srt;var y;void 0===b.srt&&(r||0===r||(y=Pd.timing||{},r=Math.max(0,y.responseStart-y.navigationStart),(0,window.isNaN)(r)&&
d.pt&&(r=d.pt)),r||0===r)&&(d.srt=Math.round(r));d.h5jse&&(n=window.location.protocol+g.m("ytplayer.config.assets.js"),(n=Pd.getEntriesByName?Pd.getEntriesByName(n)[0]:null)?d.h5jse=Math.round(d.h5jse-n.responseEnd):delete d.h5jse);b.aft=Md(a);n=b._start;if("cold"==d.yt_lt){y||(y=Pd.timing||{});var C;a:if(C=y,C.msFirstPaint)C=Math.max(0,C.msFirstPaint);else{var N=window.chrome;if(N&&(N=N.loadTimes,g.oa(N))){var N=N(),ba=1E3*Math.min(N.requestTime||window.Infinity,N.startLoadTime||window.Infinity),
ba=window.Infinity===ba?0:C.navigationStart-ba;C=Math.max(0,Math.round(1E3*N.firstPaintTime+ba)||0);break a}C=0}0<C&&C>n&&(b.fpt=C);Od(y,c);Pd.getEntriesByType&&Haa(b);(y=g.t("SPEEDINDEX_FOR_ACTIONS",void 0))&&-1<y.indexOf(h)&&(h=Ed(),y=Cd(),h=Ed()-h,0<y.Vk&&(d.si=y.Vk,b.vsc=Qd(y.ww),c.sid=h));h=[];if(window.document.querySelector&&Pd&&Pd.getEntriesByName){y={'script[name="player/base"]':"pj",'link[rel="stylesheet"][name="www-player"]':"pc",'script[name="scheduler/scheduler"]':"sj",'script[name="desktop_polymer/desktop_polymer"]':"dpj",
'link[rel="import"][name="desktop_polymer"]':"dph"};for(var la in y)if(C=window.document.querySelector(la))N="",ba=C.nodeName,"SCRIPT"==ba?N=C.src:"LINK"==ba&&(N=C.href),N&&(C=Pd.getEntriesByName(N))&&C[0]&&h.push(y[la]+"."+Math.round(C[0].duration))}h.length&&(d.rs=h.join(","))}y=Dd(a);la=y.pbr;h=y.vc;y=y.pbs;la&&h&&y&&la<h&&h<y&&1==Id(a).yt_vis&&"youtube"==k&&(Id(a).yt_lt="hot_bg",k=b.vc,la=b.pbs,delete b.aft,c.aft=Math.round(la-k));(k=g.t("PREVIOUS_ACTION"))&&(d.pa=k);d.p=g.t("CLIENT_PROTOCOL")||
"unknown";d.t=g.t("CLIENT_TRANSPORT")||"unknown";window.navigator&&window.navigator.sendBeacon&&(d.ba=1);for(var Ba in d)"_"!=Ba.charAt(0)&&(e[Ba]=d[Ba]);b.ps=Ed();d={};Ba=[];for(var Ia in b)"_"!=Ia.charAt(0)&&(C=Math.max(Math.round(b[Ia]-n),0),d[Ia]=C,Ba.push(Ia+"."+C));e.rt=Ba.join(",");b=e;Ia=[];for(var Ya in c)"_"!=Ya.charAt(0)&&Ia.push(Ya+"."+Math.round(c[Ya]));b.it=Ia.join(",");(Ya=g.m("ytdebug.logTiming"))&&Ya(e,d,c);Ld(a);g.t("EXP_DEFER_CSI_PING")?(Td(),g.l("yt.timing.deferredPingArgs_",e,
void 0),a=g.zb(Td,0),g.l("yt.timing.deferredPingTimer_",a,void 0)):Rd(e);g.zd(Iaa,new Ad(d.aft+(r||0)))}};
Gd=function(a,b){var c=g.t("TIMING_ACTION",void 0),d=Dd(b);if(g.m("yt.timing.ready_")&&c&&d._start&&Md(b)){var c=!0,e=g.t("TIMING_WAIT",[]);if(!a&&e.length)for(var h=0,k=e.length;h<k;++h)if(!(e[h]in d)){c=!1;break}(c||b)&&Ud(b)}};
Rd=function(a){if(g.t("DEBUG_CSI_DATA")){var b=g.m("yt.timing.csiData");b||(b=[],g.l("yt.timing.csiData",b,void 0));b.push({page:window.location.href,time:new Date,args:a})}g.t("EXP_DEFER_CSI_PING")&&(g.Bb(g.m("yt.timing.deferredPingTimer_")),g.l("yt.timing.deferredPingArgs_",null,void 0));var c="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",c=g.t("CSI_LOG_WITH_YT")?"/csi_204":c,b="",d;for(d in a)b+="&"+d+"="+a[d];a=c+"?"+b.substring(1);b=g.t("DOUBLE_LOG_CSI")?
"/csi_204?"+b.substring(1):null;window.navigator&&window.navigator.sendBeacon?(g.ud(a),b&&g.ud(b)):(g.td(a),b&&g.td(b));g.l("yt.timing.pingSent_",!0,void 0)};
Td=function(a){if(g.t("EXP_DEFER_CSI_PING")){var b=g.m("yt.timing.deferredPingArgs_");b&&(a&&(b.yt_fss=a),Rd(b))}};
Dd=function(a){return Nd(a).tick};
Id=function(a){return Nd(a).info};
Nd=function(a){return g.m("ytcsi."+(a||"")+"data_")||Kd(a)};
Kd=function(a){var b={tick:{},span:{},info:{}};g.l("ytcsi."+(a||"")+"data_",b,void 0);return b};
Vd=function(a){g.m("yt.timing.pingSent_")||(g.Hd("aa"),Id(void 0).ap=1,Id(void 0).yt_fss=a,Ud())};
Jaa=function(a){a=g.Wd(a);return g.Xd(a)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};
g.Xd=function(a){return null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1};
g.Wd=function(a){a=g.ld(a);return null===a?null:a.split(".").reverse()};
g.Yd=function(a,b){g.td("/gen_204?"+a,b)};
g.Zd=function(a){if(a.classList)return a.classList;a=a.className;return g.ma(a)&&a.match(/\S+/g)||[]};
g.B=function(a,b){return a.classList?a.classList.contains(b):g.Ka(g.Zd(a),b)};
g.D=function(a,b){a.classList?a.classList.add(b):g.B(a,b)||(a.className+=0<a.className.length?" "+b:b)};
g.E=function(a,b){a.classList?a.classList.remove(b):g.B(a,b)&&(a.className=(0,g.$d)(g.Zd(a),function(a){return a!=b}).join(" "))};
g.ae=function(a,b,c){c?g.D(a,b):g.E(a,b)};
g.be=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,g.u)(a.childNodes,function(a){b.appendChild(g.be(a))}):b.innerHTML=a.innerHTML;
return b};
g.ce=function(a){this.type="";this.state=this.source=this.data=this.currentTarget=this.relatedTarget=this.target=null;this.charCode=this.keyCode=0;this.shiftKey=this.ctrlKey=this.altKey=!1;this.rotation=this.clientY=this.clientX=0;this.scale=1;this.changedTouches=this.touches=null;if(a=a||window.event){this.event=a;for(var b in a)b in Kaa||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=
b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;this.Gn=a.pageX;this.Hn=a.pageY}};
g.ee=function(a,b,c,d){a.addEventListener&&("mouseenter"!=b||"onmouseenter"in window.document?"mouseleave"!=b||"onmouseenter"in window.document?"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"):b="mouseout":b="mouseover");return g.Sa(g.de,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
g.F=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=g.ee(a,b,c,d);if(e)return e;var e=++fe.count+"",h=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),k;k=h?function(d){d=new g.ce(d);if(!g.gd(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new g.ce(b);
b.currentTarget=a;return c.call(a,b)};
k=g.yb(k);a.addEventListener?("mouseenter"==b&&h?b="mouseover":"mouseleave"==b&&h?b="mouseout":"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"),a.addEventListener(b,k,d)):a.attachEvent("on"+b,k);g.de[e]=[a,b,c,k,d];return e};
g.ge=function(a){a=a||window.event;a.returnValue=!1;a.preventDefault&&a.preventDefault()};
g.ie=function(){if(null==g.m("_lact",window)){var a=(0,window.parseInt)(g.t("LACT"),10),a=(0,window.isFinite)(a)?(0,g.Sd)()-Math.max(a,0):-1;g.l("_lact",a,window);-1==a&&he();g.F(window.document,"keydown",he);g.F(window.document,"keyup",he);g.F(window.document,"mousedown",he);g.F(window.document,"mouseup",he);g.Mb("page-mouse",he);g.Mb("page-scroll",he);g.Mb("page-resize",he)}};
he=function(){null==g.m("_lact",window)&&(g.ie(),g.m("_lact",window));var a=(0,g.Sd)();g.l("_lact",a,window);g.v("USER_ACTIVE")};
g.je=function(){var a=g.m("_lact",window);return null==a?-1:Math.max((0,g.Sd)()-a,0)};
ke=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||g.Va(Laa);this.assets=a.assets||{};this.attrs=a.attrs||g.Va(Maa);this.params=a.params||g.Va(Naa);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};
g.le=function(a){a instanceof ke||(a=new ke(a));return a};
ne=function(){return null!=g.me};
g.oe=function(){return g.me?g.me.invoke():null};
pe=function(){return(0,window.parseInt)(g.t("DCLKSTAT",0),10)};
g.qe=function(a,b,c){this.A=a;this.B=b;this.C=c};
g.re=function(a){this.A=a};
g.te=function(a){a=(a.A.cookie||"").split(g.se);for(var b=[],c=[],d,e,h=0;e=a[h];h++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
g.ve=function(a,b,c,d){g.ue.set(""+a,b,c,"/",d||"youtube.com")};
g.ye=function(a,b,c){var d=g.t("VALID_SESSION_TEMPDATA_DOMAINS",[]),e=g.ld(window.location.href);e&&d.push(e);e=g.ld(a);if(g.Ka(d,e)||!e&&g.ua(a,"/"))if(a=g.md(a),a=g.nd(a))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&(we(a,b,c),xe(b))):(we(a,b),xe(b))};
we=function(a,b,c){var d=g.t("ST_BASE36",!0),e;e=g.t("ST_SHORT",!0)?"ST-":"s_tempdata-";a=e=d?e+g.Da(a).toString(36):e+g.Da(a);c=c||5;b=b?g.rd(b):"";g.ve(a,b,c)};
xe=function(a){if(a){a=a.itct||a.ved;var b=g.m("yt.logging.screenreporter.storeParentElement");a&&b&&b(new g.qe(a))}};
g.ze=function(a,b,c){c=c||"";g.zc(window.location,g.sd(a,b||{})+c)};
g.Ae=function(a,b){b&&g.ye(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):g.ze(a)};
g.Be=function(a,b,c){var d=g.t("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&g.ye(a,b);if(c)return!1;g.Ae(a);return!0};
g.Ee=function(){return g.Zc?"Webkit":g.Ce?"Moz":g.A?"ms":g.De?"O":null};
g.Fe=function(){return g.Zc?"-webkit":g.Ce?"-moz":g.A?"-ms":g.De?"-o":null};
g.Ge=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
g.He=function(a,b){return a&&b?b instanceof g.Ge?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};
g.Je=function(a,b){var c=Ie[b];if(!c){var d=Ea(b),c=d;void 0===a.style[d]&&(d=g.Ee()+g.Fa(d),void 0!==a.style[d]&&(c=d));Ie[b]=c}return c};
g.Ke=function(a,b){var c=a.style[Ea(b)];return"undefined"!==typeof c?c:a.style[g.Je(a,b)]||""};
g.Le=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};
g.Me=function(a,b){a.style.height=g.Le(b,!0)};
g.Ne=function(a,b){a.style.width=g.Le(b,!0)};
g.Oe=function(a,b){a.style.display=b?"":"none"};
g.Qe=function(){var a=g.ue.get("PREF",void 0);if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(g.Pe[d]=c.toString())}};
Re=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};
Se=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};
g.Te=function(a){a=void 0!==g.Pe[a]?g.Pe[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};
g.Ue=function(a,b){return!!((g.Te("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
g.Ve=function(a,b){(a=g.x(a))&&a.style&&(g.Oe(a,b),g.ae(a,"hid",!b))};
g.We=function(a){return(a=g.x(a))?!("none"==a.style.display||g.B(a,"hid")):!1};
Oaa=function(a){if(a=g.x(a))g.We(a)?(g.Oe(a,!1),g.D(a,"hid")):(g.Oe(a,!0),g.E(a,"hid"))};
g.G=function(a){(0,g.u)(arguments,function(a){!g.ka(a)||a instanceof window.Element?g.Ve(a,!0):(0,g.u)(a,function(a){g.G(a)})})};
g.H=function(a){(0,g.u)(arguments,function(a){!g.ka(a)||a instanceof window.Element?g.Ve(a,!1):(0,g.u)(a,function(a){g.H(a)})})};
g.Xe=function(a){(0,g.u)(arguments,function(a){g.ka(a)?(0,g.u)(a,function(a){g.Xe(a)}):Oaa(a)})};
g.Ze=function(){this.A=this.minor=this.major=0;this.C="";var a=g.m("window.navigator.plugins"),b=g.m("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,h=c.length;e<h;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.C=b;b=a;this.major=b[0];this.minor=b[1];this.A=b[2];if(0>=this.major){var k,n,r,y;if(g.Ye)try{k=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(C){k=null}else r=window.document.body,y=window.document.createElement("object"),y.setAttribute("type","application/x-shockwave-flash"),k=r.appendChild(y);if(k&&"GetVariable"in k)try{n=k.GetVariable("$version")}catch(C){n=""}r&&y&&r.removeChild(y);(k=n||
"")?(k=k.split(" ")[1].split(","),k=[(0,window.parseInt)(k[0],10)||0,(0,window.parseInt)(k[1],10)||0,(0,window.parseInt)(k[2],10)||0]):k=[0,0,0];this.major=k[0];this.minor=k[1];this.A=k[2]}};
$e=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.major>b[0]||a.major==b[0]&&a.minor>b[1]||a.major==b[0]&&a.minor==b[1]&&a.A>=b[2]};
af=function(a){return-1<a.C.indexOf("Gnash")&&-1==a.C.indexOf("AVM2")||9==a.major&&1==a.minor||9==a.major&&0==a.minor&&1==a.A?!1:9<=a.major};
Paa=function(a){return g.bf?!$e(a,11,2):g.cf?!$e(a,11,3):!af(a)};
df=function(a,b,c){if(b){a=g.ma(a)?g.Qc(a):a;var d=g.Va(c.attrs);d.tabindex=0;var e=g.Va(c.params);e.flashvars=g.rd(c.args);if(g.Ye){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var h in d)b.setAttribute(h,d[h]);for(h in e)d=window.document.createElement("param"),d.setAttribute("name",h),d.setAttribute("value",e[h]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");b.setAttribute("name",
d.id);for(h in d)b.setAttribute(h,d[h]);for(h in e)b.setAttribute(h,e[h])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};
g.gf=function(a,b){a=g.ma(a)?g.Qc(a):a;b=g.le(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=g.Ze.getInstance();$e(c,b.minVersion)?(c=ef(b,c),df(a,c,b)):ff(a,b,c)};
hf=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=g.le(a);var d=!!b,e=g.x(a.attrs.id),h=e?e.parentNode:null;if(e&&h){if(window!=window.top){var k=null;if(window.document.referrer){var n=window.document.referrer.substring(0,128);Jaa(n)||(k=n)}else k="unknown";k&&(d=!0,a.args.framer=k)}k=g.Ze.getInstance();if($e(k,a.minVersion)){var n=ef(a,k),r="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(r=e.getAttribute("src")||e.movie);(r!=n||d)&&df(h,n,a);Paa(k)&&Qaa()}else ff(h,a,k);c&&c()}else g.zb(function(){hf(a,
b,c)},50)}};
ff=function(a,b,c){0==c.major&&b.fallback?b.fallback():0==c.major&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+g.Gb("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};
ef=function(a,b){var c;(c=af(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!$e(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.url};
Qaa=function(){var a=g.x("flash10-promo-div"),b=g.Ue(g.Qe.getInstance(),107);a&&!b&&g.G(a)};
g.jf=function(a,b){var c=a.match(Raa);window.spf.style.load(a,c?c[1]:"",b)};
g.kf=function(a){g.qb.call(this);this.A=[];this.C=a||this};
lf=function(a,b,c,d){d=g.yb((0,g.p)(d,a.C));b.addEventListener(c,d);a.A.push({target:b,name:c,Zb:d})};
mf=function(a){for(;a.A.length;){var b=a.A.pop();b.target.removeEventListener(b.name,b.Zb)}};
pf=function(a,b){g.qb.call(this);this.R=this.D=a;this.la=b;this.M=!1;this.api={};this.Sa=this.X=null;this.$=new g.ub;g.tb(this,this.$);this.B={};this.F=this.ab=this.C=this.tb=this.A=null;this.ga=!1;this.Y=this.G=this.O=this.V=null;this.bb={};this.qc=["onReady"];this.ia=new g.kf(this);g.tb(this,this.ia);this.Fb=null;this.Ob=window.NaN;this.qa={};nf(this);this.ye("onDetailedError",(0,g.p)(this.ZI,this));this.ye("onTabOrderChange",(0,g.p)(this.Fy,this));this.ye("onTabAnnounce",(0,g.p)(this.vp,this));
this.ye("WATCH_LATER_VIDEO_ADDED",(0,g.p)(this.cJ,this));this.ye("WATCH_LATER_VIDEO_REMOVED",(0,g.p)(this.dJ,this));g.of||(this.ye("onMouseWheelCapture",(0,g.p)(this.GI,this)),this.ye("onMouseWheelRelease",(0,g.p)(this.HI,this)));this.ye("onAdAnnounce",(0,g.p)(this.vp,this));this.H=new g.kf(this);g.tb(this,this.H);this.kb=!1;this.fb=null};
rf=function(a,b){a.tb=b;a.A=b.clone();a.C=a.A.attrs.id||a.C;"video-player"==a.C&&(a.C=a.la,a.A.attrs.id=a.la);a.R.id==a.C&&(a.C+="-player",a.A.attrs.id=a.C);a.A.args.enablejsapi="1";a.A.args.playerapiid=a.la;a.ab||(a.ab=qf(a,a.A.args.jsapicallback||"onYouTubePlayerReady"));a.A.args.jsapicallback=null;var c=a.A.attrs.width;c&&g.Ne(a.R,Number(c)||c);(c=a.A.attrs.height)&&g.Me(a.R,Number(c)||c)};
sf=function(a){a.A.loaded||(a.A.loaded=!0,"0"!=a.A.args.autoplay?a.api.loadVideoByPlayerVars(a.A.args):a.api.cueVideoByPlayerVars(a.A.args))};
tf=function(a){if(!g.da(a.A.disable.flash)){var b=a.A.disable,c;c=$e(g.Ze.getInstance(),a.A.minVersion);b.flash=!c}return!a.A.disable.flash};
wf=function(a,b){if((!b||(5!=(Saa[b.errorCode]||5)?0:-1!=Taa.indexOf(b.errorCode)))&&tf(a)){var c=uf(a);c&&c.stopVideo&&c.stopVideo();var d=a.A;c&&c.getUpdatedConfigurationData&&(c=c.getUpdatedConfigurationData(),d=g.le(c));d.args.autoplay=1;d.args.html5_unavailable="1";rf(a,d);vf(a,"flash")}};
vf=function(a,b){if(!a.isDisposed()){if(!b){var c;if(!(c=!a.A.html5&&tf(a))){if(!g.da(a.A.disable.html5)){var d;c=!0;void 0!=a.A.args.deviceHasDisplay&&(c=a.A.args.deviceHasDisplay);if(2.2==xf)d=!0;else{a:{var e=c;c=g.m("yt.player.utils.videoElement_");c||(c=window.document.createElement("video"),g.l("yt.player.utils.videoElement_",c,void 0));try{if(c.canPlayType)for(var e=e?Uaa:Vaa,h=0;h<e.length;h++)if(c.canPlayType(e[h])){d=null;break a}d="fmt.noneavailable"}catch(k){d="html5.missingapi"}}d=!d}d&&
(d=yf(a)||a.A.assets.js);a.A.disable.html5=!d;d||(a.A.args.html5_unavailable="1")}c=!!a.A.disable.html5}b=c?tf(a)?"flash":"unsupported":"html5"}("flash"==b?a.UO:"html5"==b?a.VO:a.WO).call(a)}};
yf=function(a){var b=!0,c=uf(a);c&&a.A&&(a=a.A,b=g.w(c,"version")==a.assets.js);return b&&!!g.m("yt.player.Application.create")};
uf=function(a){var b=g.x(a.C);!b&&a.R&&a.R.querySelector&&(b=a.R.querySelector("#"+a.C));return b};
zf=function(a,b,c){var d=b[c];return function(){try{return a.Fb=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.Fb=e,g.Db(e,"WARNING"))}}};
nf=function(a){a.M=!1;if(a.Sa)for(var b in a.B)a.Sa(b,a.B[b]);for(var c in a.qa)g.Bb((0,window.parseInt)(c,10));a.qa={};a.X=null;a.Sa=null;for(var d in a.api)a.api[d]=null;a.api.addEventListener=(0,g.p)(a.ye,a);a.api.removeEventListener=(0,g.p)(a.YM,a);a.api.destroy=(0,g.p)(a.dispose,a);a.api.getLastError=(0,g.p)(a.dA,a);a.api.getPlayerType=(0,g.p)(a.sA,a);a.api.getCurrentVideoConfig=(0,g.p)(a.Dz,a);a.api.loadNewVideoConfig=(0,g.p)(a.Ro,a);a.api.isReady=(0,g.p)(a.iP,a)};
qf=function(a,b){var c=b;if("string"==typeof b){if(a.bb[b])return a.bb[b];c=function(){var a=g.m(b);a&&a.apply(g.ea,arguments)};
a.bb[b]=c}return c?c:null};
Waa=function(a,b){var c="ytPlayer"+b+a.la;a.B[b]=c;g.ea[c]=function(c){var e=g.zb(function(){a.isDisposed()||(a.$.ma(b,c),g.Ta(a.qa,String(e)))},0);
g.Ua(a.qa,String(e),!0)};
return c};
Af=function(a){return(a=uf(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
Bf=function(a){g.Hd("dcp");a.cancel();nf(a);a.F=null;a.A&&(a.A.loaded=!1);var b=uf(a);"html5"==Af(a)?a.O=b:b&&b.destroy&&b.destroy();g.cd(a.D);mf(a.ia);a.G=null;a.Y=null};
g.Ef=function(a,b){a=g.ma(a)?g.Qc(a):a;b=g.le(b);var c=g.Cf+"_"+g.ra(a),d=g.Df[c];if(d)return d.Ro(b),d.api;d=new pf(a,c);g.Df[c]=d;g.v("player-added",d.api);g.rb(d,g.sa(Xaa,d));g.zb(function(){d.Ro(b)},0);
return d.api};
Xaa=function(a){g.Df[a.getId()]=null};
g.Ff=function(a){a=g.x(a);if(!a)return null;var b=g.Cf+"_"+g.ra(a),c=g.Df[b];c||(c=new pf(a,b),g.Df[b]=c);return c.api};
g.Gf=function(){return g.B(g.x("page-container"),"remote-connected")};
Yaa=function(){g.l("yt.abuse.botguardInitialized",ne,void 0);g.l("yt.abuse.invokeBotguard",g.oe,void 0);g.l("yt.abuse.dclkstatus.checkDclkStatus",pe,void 0);g.l("yt.player.exports.navigate",g.Be,void 0);g.l("yt.player.embed",g.Ef,void 0);g.l("yt.player.getPlayerByElement",g.Ff,void 0);g.l("yt.util.activity.init",g.ie,void 0);g.l("yt.util.activity.getTimeSinceActive",g.je,void 0);g.l("yt.util.activity.setTimestamp",he,void 0);var a=g.m("ytplayer.config");Hf(a);g.m("ytspf.enabled")&&(If=g.Ab(Jf,5E3),
(a=g.Kf())?(a.addEventListener("onReady",Jf),a.addEventListener("onStateChange",Jf)):Lf("unable to init PP monitor"))};
Hf=function(a){for(var b in g.Df){var c=g.Df[b];c&&c.cancel()}if(a=a||null){b=g.Kf();var d=!0,c=g.Mf;g.Mf=null;b&&b.getVideoData&&c&&(d=b.getVideoData(),d=!!c.fullscreen||d.video_id!=a.args.video_id||d.list!=a.args.list||d.video_id!=c.videoId||d.list!=c.listId);d?(Nf="",g.Ef("player-api",a)):b.playVideo();a=g.le(a);a.loaded=!0}Jf();g.l("ytplayer.config",a,void 0)};
g.Kf=function(){var a=g.m("yt.player.getPlayerByElement");return a?a("player-api"):null};
Jf=function(){var a=g.Kf();if(a){var b;b=g.x("player");b=!b||g.B(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==g.t("PAGE_NAME"),e=g.Gf();!c||d||e||(Lf("PP playing off watch (paused)"),a.pauseVideo());b&&d?Lf("PP off-screen on watch"):b||d||Lf("PP !off-screen off watch")}};
Lf=function(a){var b=g.t("PAGE_NAME");b&&(b=[b,Nf,g.m("_spf_state.nav-counter")],a+="("+b.join(",")+")",g.l("yt.www.persistentplayer.issue",a,void 0),g.Db(Error(a),"WARNING"))};
Pf=function(){g.Hd("ol");g.t("CSI_TICK_PAINT_TIME")?window.requestAnimationFrame&&!window.document.hidden?window.requestAnimationFrame(function(){(0,window.setTimeout)(function(){g.Hd("cpt");Of()},0)}):window.document.hidden?(g.Hd("cpt"),Of()):(0,window.setTimeout)(function(){g.Hd("cpt");
Of()},0):Of()};
Of=function(){Qf("init");var a=g.t("PAGE_NAME",void 0);a&&Qf("init-"+a)};
Qf=function(a){g.Pb()?Rf.push(g.Qb(g.sa(g.Ob,a),0)):g.v(a)};
Sf=function(){g.Tb(Rf);Rf.length=0;var a=g.t("PAGE_NAME",void 0);a&&g.Ob("dispose-"+a);g.Ob("dispose")};
Zaa=function(){Pf()};
$aa=function(){g.t("TIMING_REPORT_ON_UNLOAD")&&Gd(!0);Vd("u");Td("u");Sf();g.Ob("pageunload")};
aba=function(a,b,c,d,e){for(var h=window.document.getElementsByTagName("script"),k=!1,n=0,r=h.length;n<r;n++)if(0<h[n].src.indexOf("/debug-")){k=!0;break}k&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),g.Db(e))};
Tf=function(){he()};
Uf=function(){g.t("EXP_LACT_HISTORY")&&he()};
Zf=function(){Vf=1;Wf=Xf=0;g.t("TIMING_REPORT_ON_UNLOAD")&&Gd(!0);Vd("n");Td("n");Ld();Jd("n");Fd("mark_navigation_requested");Yf(bba);g.Ob("navigate")};
cg=function(a){a=a.detail.part||a.detail.partial;g.Hd("nc"+Xf);++Xf;if(!a.data||!a.data.deferDispose){var b=1==Vf;Vf=2;b?(Yf(cba),$f()):Yf(dba);if(b=a.data&&a.data.swfcfg)ag(a.timing,b.args),bg(b)}};
dg=function(){g.Hd("np"+Wf);++Wf};
eg=function(a){a=a.detail.response;var b=1==Vf;Vf=3;b&&(Yf(eba),$f());if(b=a.data&&a.data.swfcfg)ag(a.timing,b.args),bg(b)};
hg=function(a){g.Hd("nd");a=a.detail.response;g.fg=a.cacheKey;a=a.timing;var b=window._spf_state,b=b&&b["nav-counter"]||0;Id(void 0).yt_nav=b;Jd("ne",a.responseStart);b=Math.max(0,a.responseStart-a.navigationStart);Id(void 0).srt=b;b=a.spfCached?"hot":"warm";Id(void 0).yt_lt=b;b=+!!a.spfPrefetched;Id(void 0).yt_pft=b;g.Hd("pfs",a.fetchStart);var b=a.responseStart,c=Nd(void 0).span,d=Dd(void 0);"pfs"in d&&(c.preq=(b||Ed())-d.pfs);"redirectStart"in a&&Od(a);Yf(gg);window.document.getElementById("content").style.height=
"";Pf();Vf=0};
ig=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),g.Db(a)};
jg=function(a){g.Yd(g.rd({spfreload:"1",url:a.detail.url,reason:a.detail.reason}))};
gba=function(){fba()};
hba=function(){};
$f=function(){var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");Sf();var a=g.t("TIMING_ACTION"),b;for(b in g.wb)delete g.wb[b];g.xb("PREVIOUS_ACTION",a);g.l("ytplayer.config",null,void 0);if((b=g.Kf())&&b.stopVideo){if(b.stopVideo(),b=b.getLastError())Nf=b,(b=g.x("movie_player"))&&b.stopVideo?(b.stopVideo(),Nf="recovered"):Nf="missing2"}else Nf="missing";Jf()};
bg=function(a){"cfg"in Dd(void 0)||g.Hd("cfg");Hf(a)};
Yf=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));g.Sb(kg);kg=g.Rb(function(){var c=a[0],d=a[1],e=a[2];b.className="";var h=b.style;h.transitionDuration=h.webkitTransitionDuration=c+"ms";h.width=d+"%";g.Bb(lg);lg=g.zb(function(){b.className=e},c)},0)};
fba=function(){var a=gg[0]+50;g.Bb(lg);lg=g.zb(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
ag=function(a,b){var c=a&&a.spfCached,d=a&&a.spfPrefetched,e=[];c&&!d&&(0,g.u)(iba,function(a){a in b&&(delete b[a],e.push(a))});
g.t("EXP_DEBUG_PREFETCH")&&(e.sort(),c={a:"removeNonCacheableVideoVars",cached:c,prefetched:d,deleted:e.join("")},g.Yd(g.rd(c)))};
mg=function(){g.Ub.call(this,"www/base");this.B=0};
ng=function(a){(a=a.detail.name)&&Xb(a)};
g.aa=[];g.og=g.og||{};g.ea=this;qa="closure_uid_"+(1E9*Math.random()>>>0);aaa=0;g.Sd=Date.now||function(){return+new Date};g.ta[" "]=g.fa;var eaa,faa,gaa,haa,iaa,jaa,daa;g.za=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
eaa=/&/g;faa=/</g;gaa=/>/g;haa=/"/g;iaa=/'/g;jaa=/\x00/g;daa=/[\x00&<>"']/;g.pg=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
g.jba=2147483648*Math.random()|0;g.Ja=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;
if(g.ma(a))return g.ma(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
g.kba=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;
0>c&&(c=Math.max(0,a.length+c));if(g.ma(a))return g.ma(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
g.u=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ma(a)?a.split(""):a,h=0;h<d;h++)h in e&&b.call(c,e[h],h,a)};
g.$d=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],h=0,k=g.ma(a)?a.split(""):a,n=0;n<d;n++)if(n in k){var r=k[n];
b.call(c,r,n,a)&&(e[h++]=r)}return e};
g.qg=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),h=g.ma(a)?a.split(""):a,k=0;k<d;k++)k in h&&(e[k]=b.call(c,h[k],k,a));
return e};
g.rg=Array.prototype.reduce?function(a,b,c,d){d&&(b=(0,g.p)(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;
(0,g.u)(a,function(c,k){e=b.call(d,e,c,k,a)});
return e};
g.sg=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ma(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&b.call(c,e[h],h,a))return!0;
return!1};
g.tg=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ma(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&!b.call(c,e[h],h,a))return!1;
return!0};g.ug=g.Oa(!1);g.vg=g.Oa(!0);g.wg=g.Oa(null);var Wa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");a:{var xg=g.ea.navigator;if(xg){var yg=xg.userAgent;if(yg){g.Za=yg;break a}}g.Za=""};var pb;g.db.prototype.get=function(){var a;0<this.C?(this.C--,a=this.A,this.A=a.next,a.next=null):a=this.B();return a};var lb=new g.db(function(){return new gb},function(a){a.reset()},100);
fb.prototype.remove=function(){var a=null;this.A&&(a=this.A,this.A=this.A.next,this.A||(this.C=null),a.next=null);return a};
gb.prototype.set=function(a,b){this.Fe=a;this.scope=b;this.next=null};
gb.prototype.reset=function(){this.next=this.scope=this.Fe=null};var ib,jb=!1,kb=new fb;g.qb.prototype.Hd=!1;g.qb.prototype.isDisposed=function(){return this.Hd};
g.qb.prototype.dispose=function(){this.Hd||(this.Hd=!0,this.W())};
g.qb.prototype.W=function(){if(this.Ib)for(;this.Ib.length;)this.Ib.shift()()};g.q(g.ub,g.qb);g.f=g.ub.prototype;g.f.subscribe=function(a,b,c){var d=this.Fd[a];d||(d=this.Fd[a]=[]);var e=this.D;this.A[e]=a;this.A[e+1]=b;this.A[e+2]=c;this.D=e+3;d.push(e);return e};
g.f.unsubscribe=function(a,b,c){if(a=this.Fd[a]){var d=this.A;if(a=g.Ha(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.Gd(a)}return!1};
g.f.Gd=function(a){var b=this.A[a];if(b){var c=this.Fd[b];0!=this.B?(this.C.push(a),this.A[a+1]=g.fa):(c&&g.Ma(c,a),delete this.A[a],delete this.A[a+1],delete this.A[a+2])}return!!b};
g.f.ma=function(a,b){var c=this.Fd[a];if(c){for(var d=Array(arguments.length-1),e=1,h=arguments.length;e<h;e++)d[e-1]=arguments[e];if(this.F)for(e=0;e<c.length;e++){var k=c[e];maa(this.A[k+1],this.A[k+2],d)}else{this.B++;try{for(e=0,h=c.length;e<h;e++)k=c[e],this.A[k+1].apply(this.A[k+2],d)}finally{if(this.B--,0<this.C.length&&0==this.B)for(;c=this.C.pop();)this.Gd(c)}}return 0!=e}return!1};
g.f.clear=function(a){if(a){var b=this.Fd[a];b&&((0,g.u)(b,this.Gd,this),delete this.Fd[a])}else this.A.length=0,this.Fd={}};
g.f.sb=g.ca(1);g.f.W=function(){g.ub.N.W.call(this);this.clear();this.C.length=0};var Ed;g.wb=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};g.l("yt.config_",g.wb,void 0);g.l("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);g.Eb=window.yt&&window.yt.msgs_||g.m("window.ytcfg.msgs")||{};g.l("yt.msgs_",g.Eb,void 0);Ed=window.performance&&window.performance.timing&&window.performance.now&&window.__yt_experimental_now?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()};
g.Ye="Microsoft Internet Explorer"==window.navigator.appName;var lba=g.m("yt.pubsub.instance_")||new g.ub;g.ub.prototype.subscribe=g.ub.prototype.subscribe;g.ub.prototype.unsubscribeByKey=g.ub.prototype.Gd;g.ub.prototype.publish=g.ub.prototype.ma;g.ub.prototype.clear=g.ub.prototype.clear;g.l("yt.pubsub.instance_",lba,void 0);var Jb=g.m("yt.pubsub.subscribedKeys_")||{};g.l("yt.pubsub.subscribedKeys_",Jb,void 0);var Lb=g.m("yt.pubsub.topicToKeys_")||{};g.l("yt.pubsub.topicToKeys_",Lb,void 0);var Kb=g.m("yt.pubsub.isSynchronous_")||{};
g.l("yt.pubsub.isSynchronous_",Kb,void 0);var Ib=g.m("yt.pubsub.skipSubId_")||null;g.l("yt.pubsub.skipSubId_",Ib,void 0);g.f=g.Ub.prototype;g.f.lN=function(){this.dk()||this.init()};
g.f.enable=function(){this.A=1;(0,g.u)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.lN,this),this.subscribe("dispose-"+a,this.dispose,this),g.t("PAGE_NAME")==a&&g.Vb(this))},this)};
g.f.init=function(){g.Sb(this.C);this.A=2;this.G&&this.G()};
g.f.dk=function(){return 2==this.A};
g.f.dispose=function(){this.A=3;g.Sb(this.C);this.F&&this.F()};
g.f.disable=function(){this.A=4;this.clear();try{this.dispose()}catch(a){g.Db(a)}};
g.f.subscribe=function(a,b,c){a=g.Mb(a,b,c);this.D.push(a);return a};
g.f.clear=function(){g.Nb(this.D);this.D=[]};var Wb=g.m("yt.modules.registry_")||{};g.l("yt.modules.registry_",Wb,void 0);var saa={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};g.mba=RegExp("[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.nba=RegExp("^[^\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.zg=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");g.$b.prototype.Zf=!0;g.$b.prototype.af=function(){return this.A};
g.$b.prototype.toString=function(){return"Const{"+this.A+"}"};
var Zb={};cc.prototype.Zf=!0;var bc={};cc.prototype.af=function(){return this.A};
var oaa=ec(""),naa=/^([-,."'%_!# a-zA-Z0-9]+|(?:rgb|hsl)a?\([0-9.%, ]+\))$/;g.hc.prototype.Zf=!0;g.hc.prototype.af=function(){return this.A};
g.hc.prototype.Rm=!0;g.hc.prototype.Hg=function(){return 1};
var paa=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,gc={};g.jc("about:blank");g.mc.prototype.Zf=!0;g.mc.prototype.af=function(){return this.A};
g.mc.prototype.Rm=!0;g.mc.prototype.Hg=function(){return 1};
var lc={};var uc,raa,qaa,oc;g.pc.prototype.Rm=!0;g.pc.prototype.Hg=function(){return this.C};
g.pc.prototype.Zf=!0;g.pc.prototype.af=function(){return this.A};
uc=/^[a-zA-Z0-9-]+$/;raa={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};qaa={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,META:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};oc={};g.oba=g.sc("<!DOCTYPE html>",0);g.Ag=g.sc("",0);g.Bg=g.sc("<br>",0);var Cc={};var taa=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,uaa=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;g.pba=Math.sign||function(a){return 0<a?1:0>a?-1:a};g.f=g.Gc.prototype;g.f.clone=function(){return new g.Gc(this.x,this.y)};
g.f.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};
g.f.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
g.f.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.f.scale=function(a,b){var c=g.na(b)?b:a;this.x*=a;this.y*=c;return this};g.f=g.Hc.prototype;g.f.clone=function(){return new g.Hc(this.width,this.height)};
g.f.area=function(){return this.width*this.height};
g.f.aspectRatio=function(){return this.width/this.height};
g.f.isEmpty=function(){return!this.area()};
g.f.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.f.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.f.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.f.scale=function(a,b){var c=g.na(b)?b:a;this.width*=a;this.height*=c;return this};var Eg,Fg,Kc,Jg;g.De=ab();g.A=g.$a("Trident")||g.$a("MSIE");g.Cg=g.$a("Edge");g.Dg=g.Cg||g.A;g.Ce=g.$a("Gecko")&&!(g.xa(g.Za.toLowerCase(),"webkit")&&!g.$a("Edge"))&&!(g.$a("Trident")||g.$a("MSIE"))&&!g.$a("Edge");g.Zc=g.xa(g.Za.toLowerCase(),"webkit")&&!g.$a("Edge");g.Zc&&g.$a("Mobile");g.cf=g.$a("Macintosh");g.bf=g.$a("Windows");g.qba=g.$a("Linux")||g.$a("CrOS");Eg=g.ea.navigator||null;Eg&&g.xa(Eg.appVersion||"","X11");g.rba=g.$a("Android");g.sba=g.Ic();g.tba=g.$a("iPad");
a:{var Gg="",Hg=function(){var a=g.Za;if(g.Ce)return/rv\:([^\);]+)(\)|;)/.exec(a);if(g.Cg)return/Edge\/([\d\.]+)/.exec(a);if(g.A)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(g.Zc)return/WebKit\/(\S+)/.exec(a);if(g.De)return/(?:Version)[ \/]?(\S+)/.exec(a)}();
Hg&&(Gg=Hg?Hg[1]:"");if(g.A){var Ig=Jc();if(null!=Ig&&Ig>(0,window.parseFloat)(Gg)){Fg=String(Ig);break a}}Fg=Gg}g.Lc=Fg;Kc={};Jg=g.ea.document;g.Oc=Jg&&g.A?Jc()||("CSS1Compat"==Jg.compatMode?(0,window.parseInt)(g.Lc,10):5):void 0;var vaa;vaa=!g.A||g.Pc(9);g.uba=!g.Ce&&!g.A||g.A&&g.Pc(9)||g.Ce&&g.Nc("1.9.1");g.Kg=g.A&&!g.Nc("9");g.vba=g.A||g.De||g.Zc;g.wba=g.A&&!g.Pc(9);var Sc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};g.Lg="StopIteration"in g.ea?g.ea.StopIteration:{message:"StopIteration",stack:""};g.jd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;g.of=g.$a("Firefox");g.Mg=g.Ic()||g.$a("iPod");g.Ng=g.$a("iPad");g.xba=g.$a("Android")&&!(bb()||g.$a("Firefox")||ab()||g.$a("Silk"));g.Og=bb();g.Pg=g.$a("Safari")&&!(bb()||g.$a("Coast")||ab()||g.$a("Edge")||g.$a("Silk")||g.$a("Android"))&&!(g.Ic()||g.$a("iPad")||g.$a("iPod"));var vd={},Aaa=0,yba=g.m("yt.net.ping.workerUrl_")||null;g.l("yt.net.ping.workerUrl_",yba,void 0);g.wd.prototype.Yb=g.ca(2);g.xd.prototype.toString=function(){return this.topic};var zba=g.m("yt.pubsub2.instance_")||new g.ub;g.ub.prototype.subscribe=g.ub.prototype.subscribe;g.ub.prototype.unsubscribeByKey=g.ub.prototype.Gd;g.ub.prototype.publish=g.ub.prototype.ma;g.ub.prototype.clear=g.ub.prototype.clear;g.l("yt.pubsub2.instance_",zba,void 0);g.Qg=g.m("yt.pubsub2.subscribedKeys_")||{};g.l("yt.pubsub2.subscribedKeys_",g.Qg,void 0);g.Rg=g.m("yt.pubsub2.topicToKeys_")||{};g.l("yt.pubsub2.topicToKeys_",g.Rg,void 0);g.Sg=g.m("yt.pubsub2.isAsync_")||{};
g.l("yt.pubsub2.isAsync_",g.Sg,void 0);g.l("yt.pubsub2.skipSubKey_",null,void 0);g.q(Ad,g.wd);var Iaa=new g.xd("timing-sent",Ad);var Baa=/url\(["']?(http[^'"\)]+)['"]?\)/i;var Pd=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},Gaa=(0,g.p)(Pd.clearResourceTimings||Pd.webkitClearResourceTimings||Pd.mozClearResourceTimings||Pd.msClearResourceTimings||Pd.oClearResourceTimings||g.fa,Pd),Fd=Pd.mark?function(a){Pd.mark(a)}:g.fa;g.Aba=g.Zc?"webkit":g.Ce?"moz":g.A?"ms":g.De?"o":"";g.Tg=g.m("yt.dom.getNextId_");if(!g.Tg){g.Tg=function(){return++Bba};
g.l("yt.dom.getNextId_",g.Tg,void 0);var Bba=0};g.ce.prototype.preventDefault=function(){this.event&&(this.event.returnValue=!1,this.event.preventDefault&&this.event.preventDefault())};
g.ce.prototype.stopPropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopPropagation&&this.event.stopPropagation())};
g.ce.prototype.stopImmediatePropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopImmediatePropagation&&this.event.stopImmediatePropagation())};
var Kaa={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1,webkitMovementX:1,webkitMovementY:1};g.de=g.m("yt.events.listeners_")||{};g.l("yt.events.listeners_",g.de,void 0);var fe=g.m("yt.events.counter_")||{count:0};g.l("yt.events.counter_",fe,void 0);var Laa={enablejsapi:1},Maa={},Naa={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};ke.prototype.clone=function(){var a=new ke,b;for(b in this)if(this.hasOwnProperty(b)){var c=this[b];"object"==g.ha(c)?a[b]=g.Va(c):a[b]=c}return a};g.me=null;g.se=/\s*;\s*/;g.f=g.re.prototype;g.f.isEnabled=function(){return window.navigator.cookieEnabled};
g.f.set=function(a,b,c,d,e,h){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');g.da(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";h=h?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,g.Sd)()+1E3*c)).toUTCString();this.A.cookie=a+"="+b+e+d+c+h};
g.f.get=function(a,b){for(var c=a+"=",d=(this.A.cookie||"").split(g.se),e=0,h;h=d[e];e++){if(0==h.lastIndexOf(c,0))return h.substr(c.length);if(h==a)return""}return b};
g.f.remove=function(a,b,c){var d=g.da(this.get(a));this.set(a,"",0,b,c);return d};
g.f.Sb=g.ca(3);g.f.pb=g.ca(4);g.f.isEmpty=function(){return!this.A.cookie};
g.f.sb=g.ca(0);g.f.Ee=g.ca(5);g.f.clear=function(){for(var a=g.te(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
g.ue=new g.re(window.document);g.ue.C=3950;g.Ug=g.A?"focusin":"DOMFocusIn";g.Cba=g.A?"focusout":"DOMFocusOut";g.Vg=g.Zc?"webkitTransitionEnd":g.De?"otransitionend":"transitionend";g.f=g.Ge.prototype;g.f.getHeight=function(){return this.bottom-this.top};
g.f.clone=function(){return new g.Ge(this.top,this.right,this.bottom,this.left)};
g.f.contains=function(a){return g.He(this,a)};
g.f.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
g.f.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
g.f.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
g.f.scale=function(a,b){var c=g.na(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};var Ie;Ie={};g.Wg=g.Ce?"MozUserSelect":g.Zc||g.Cg?"WebkitUserSelect":null;g.ga(g.Qe);g.Pe=g.m("yt.prefs.UserPrefs.prefs_")||{};g.l("yt.prefs.UserPrefs.prefs_",g.Pe,void 0);g.f=g.Qe.prototype;g.f.get=function(a,b){Se(a);Re(a);var c=void 0!==g.Pe[a]?g.Pe[a].toString():null;return null!=c?c:b?b:""};
g.f.set=function(a,b){Se(a);Re(a);if(null==b)throw"ExpectedNotNull";g.Pe[a]=b.toString()};
g.f.remove=function(a){Se(a);Re(a);delete g.Pe[a]};
g.f.save=function(){var a;a=[];for(var b in g.Pe)a.push(b+"="+(0,window.escape)(g.Pe[b]));a=a.join("&");g.ve("PREF",a,63072E3)};
g.f.clear=function(){g.Pe={}};g.Xg=g.Pa(function(){if(g.A)return g.Nc("10.0");var a=window.document.createElement("DIV"),b=g.Fe(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");g.yc(a,g.wc("div",{style:c}));return""!=g.Ke(a.firstChild,"transition")});g.ga(g.Ze);g.Ze.prototype.getVersion=function(){return[this.major,this.minor,this.A]};var Raa=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var xf;var Yg=g.Za,Yg=Yg.toLowerCase();if(g.xa(Yg,"android")){var Zg=Yg.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(Zg)xf=Number(Zg[1]);else{var $g={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},ah=Yg.match("("+g.Ra($g).join("|")+")");xf=ah?$g[ah[0]]:0}}else xf=void 0;var Uaa=['video/mp4; codecs="avc1.42001E, mp4a.40.2"','video/webm; codecs="vp8.0, vorbis"'],Vaa=['audio/mp4; codecs="mp4a.40.2"'];g.q(g.kf,g.qb);g.kf.prototype.Xa=g.ca(6);g.kf.prototype.W=function(){mf(this);g.kf.N.W.call(this)};var Saa={"api.invalidparam":2,auth:150,"drm.auth":150,heartbeat:150,"html5.unsupportedads":5,"fmt.noneavailable":5,"fmt.decode":5,"fmt.unplayable":5,"html5.missingapi":5,"drm.unavailable":5};g.q(pf,g.qb);var Taa=["drm.unavailable","fmt.noneavailable","html5.missingapi","html5.unsupportedads","html5.unsupportedlive"];g.f=pf.prototype;g.f.getId=function(){return this.la};
g.f.Ro=function(a,b){this.isDisposed()||(rf(this,a),vf(this,b),this.M&&sf(this))};
g.f.Dz=function(){return this.tb};
g.f.VO=function(){if(!this.ga){var a=yf(this);a&&"html5"==Af(this)?(this.F="html5",this.M||this.$g()):(Bf(this),this.F="html5",a&&this.O?(this.D.appendChild(this.O),this.$g()):(this.A.loaded=!0,this.V=(0,g.p)(function(){var a=this.D,c=this.A.clone();g.m("yt.player.Application.create")(a,c);this.$g()},this),this.ga=!0,a?this.V():(g.Ec(this.A.assets.js,this.V),g.jf(this.A.assets.css))))}};
g.f.UO=function(){var a=this.A.clone();if(!this.G){var b=uf(this);b&&(this.G=window.document.createElement("span"),this.G.tabIndex=0,lf(this.ia,this.G,"focus",this.Vt),this.Y=window.document.createElement("span"),this.Y.tabIndex=0,lf(this.ia,this.Y,"focus",this.Vt),g.dd(this.G,b),g.ed(this.Y,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==Af(this)?(this.F="flash",this.M||hf(a,!1,(0,g.p)(this.$g,this))):(Bf(this),this.F="flash",this.A.loaded=!0,g.gf(this.D,a),
this.$g())};
g.f.Vt=function(){uf(this).focus()};
g.f.$g=function(){if(!this.isDisposed()){var a=uf(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(h){}if(b)if(this.ga=!1,a.isNotServable&&a.isNotServable(this.A.args.video_id))wf(this);else{nf(this);this.M=!0;a=uf(this);a.addEventListener&&(this.X=zf(this,a,"addEventListener"));a.removeEventListener&&(this.Sa=zf(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),c=0;c<b.length;c++){var d=b[c];this.api[d]||(this.api[d]=zf(this,
a,d))}for(var e in this.B)this.X(e,this.B[e]);sf(this);this.ab&&this.ab(this.api);this.$.ma("onReady",this.api)}else this.Ob=g.zb((0,g.p)(this.$g,this),50)}};
g.f.iP=function(){return this.M};
g.f.ye=function(a,b){if(!this.isDisposed()){var c=qf(this,b);if(c){if(!g.Ka(this.qc,a)&&!this.B[a]){var d=Waa(this,a);this.X&&this.X(a,d)}this.$.subscribe(a,c);"onReady"==a&&this.M&&g.zb(g.sa(c,this.api),0)}}};
g.f.YM=function(a,b){if(!this.isDisposed()){var c=qf(this,b);c&&this.$.unsubscribe(a,c)}};
g.f.Fy=function(a){a=a?yaa:xaa;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.G||b==this.Y||(b.focus(),b!=window.document.activeElement));)b=a(b)};
g.f.vp=function(a){g.v("a11y-announce",a)};
g.f.ZI=function(a){wf(this,a)};
g.f.cJ=function(a){g.v("WATCH_LATER_VIDEO_ADDED",a)};
g.f.dJ=function(a){g.v("WATCH_LATER_VIDEO_REMOVED",a)};
g.f.GI=function(){this.kb||(g.Og?(this.fb=g.Yc(window.document),lf(this.H,window,"scroll",this.iL),lf(this.H,this.D,"touchmove",this.QK)):(lf(this.H,this.D,"mousewheel",this.ku),lf(this.H,this.D,"wheel",this.ku)),this.kb=!0)};
g.f.HI=function(){mf(this.H);this.kb=!1};
g.f.ku=function(a){g.ge(a)};
g.f.iL=function(){window.scrollTo(this.fb.x,this.fb.y)};
g.f.QK=function(a){a.preventDefault()};
g.f.WO=function(){Bf(this);this.F="unsupported";var a='Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a='Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');
b=this.A.messages.player_fallback||a;a=g.x("player-unavailable");g.x("unavailable-submessage")&&a&&(g.x("unavailable-submessage").innerHTML=b,(b=g.z("icon",a))&&g.Bc(b,"icon")&&(b.src=g.w(b,"icon")),g.Oe(a,!0),g.D(g.x("player"),"off-screen-trigger"))};
g.f.sA=function(){return this.F||Af(this)};
g.f.dA=function(){return this.Fb};
g.f.cancel=function(){this.V&&g.Fc(this.A.assets.js,this.V);g.Bb(this.Ob);this.ga=!1};
g.f.W=function(){Bf(this);if(this.O&&this.A)try{this.O.destroy()}catch(b){g.Db(b)}this.bb=null;for(var a in this.B)g.ea[this.B[a]]=null;this.tb=this.A=this.api=null;delete this.D;delete this.R;pf.N.W.call(this)};g.Df={};g.Cf="player_uid_"+(1E9*Math.random()>>>0);var Dba=g.m("yt.abuse.botguardInitialized")||ne;g.l("yt.abuse.botguardInitialized",Dba,void 0);var Eba=g.m("yt.abuse.invokeBotguard")||g.oe;g.l("yt.abuse.invokeBotguard",Eba,void 0);var Fba=g.m("yt.abuse.dclkstatus.checkDclkStatus")||pe;g.l("yt.abuse.dclkstatus.checkDclkStatus",Fba,void 0);var Gba=g.m("yt.player.exports.navigate")||g.Be;g.l("yt.player.exports.navigate",Gba,void 0);var Hba=g.m("yt.player.embed")||g.Ef;g.l("yt.player.embed",Hba,void 0);var Iba=g.m("yt.player.getPlayerByElement")||g.Ff;
g.l("yt.player.getPlayerByElement",Iba,void 0);var Jba=g.m("yt.util.activity.init")||g.ie;g.l("yt.util.activity.init",Jba,void 0);var Kba=g.m("yt.util.activity.getTimeSinceActive")||g.je;g.l("yt.util.activity.getTimeSinceActive",Kba,void 0);var Lba=g.m("yt.util.activity.setTimestamp")||he;g.l("yt.util.activity.setTimestamp",Lba,void 0);var If,Nf;g.Mf=null;Nf="";var Rf=[];var Vf,lg,kg,Xf,Wf,iba,bba,eba,cba,dba,gg;Xf=0;Wf=0;iba=["server_prefetched_vast","vmap"];bba=[900,60,"waiting"];eba=[500,99,"waiting"];cba=[300,60,"waiting"];dba=[400,99,"waiting"];gg=[300,101,"done"];window.yt=window.yt||{};g.l("yt.setConfig",g.xb,void 0);g.l("yt.getConfig",g.t,void 0);g.l("yt.hasMsg",g.Fb,void 0);g.l("yt.pubsub.publish",g.v,void 0);g.l("yt.pubsub.subscribe",g.Mb,void 0);g.l("yt.setMsg",function(a){vb(g.Eb,arguments)},void 0);
g.l("yt.setGoogMsg",function(a){vb(g.Eb,arguments)},void 0);
g.l("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+Math.round(a[e]));c.rt=d.join(",");for(var h in b)"_"!=h.charAt(0)&&(c[h]=b[h]);a=g.t("TIMING_INFO",{});"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);Rd(c)},void 0);
g.l("ytcsi.tick",g.Hd,void 0);g.q(mg,g.Ub);
mg.prototype.enable=function(){window.onload=Zaa;window.onunload=$aa;window.onerror=aba;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfclick",Tf),window.addEventListener("spfhistory",Uf),window.addEventListener("spfrequest",Zf),window.addEventListener("spfpartprocess",cg),window.addEventListener("spfpartdone",dg),window.addEventListener("spfprocess",eg),window.addEventListener("spfdone",hg),window.addEventListener("spferror",ig),window.addEventListener("spfreload",
jg),window.addEventListener("spfjsbeforeunload",ng)),a.config=a.config||{},window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",gba),this.subscribe("dispose",hba)):window.spf.dispose();
this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
mg.prototype.init=function(){mg.N.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&g.t("PAGEFRAME_JS")?(b=g.t("PAGEFRAME_JS",void 0),c=function(){window.ytPageFrameLoaded=!0;g.m("ytbin.www.pageframe.setup")()}):a&&(a=g.m("yt.www.masthead.loadSearchbox"))&&a();
var a=g.t("JS_COMMON_MODULE"),d=g.t("JS_PAGE_MODULES");d||(d=[a]);a=g.t("JS_DELAY_LOAD",0);0<a?(g.Bb(this.B),this.B=g.zb(function(){b&&g.Ec(b,c);window.spf.script.require(d)},a)):(b&&g.Ec(b,c),window.spf.script.require(d));
Yaa();g.l("yt.timing.ready_",!0,void 0);Gd(!1);var a=!!g.m("yt.reactLoaded"),e=g.t("REACT_JS",void 0);!a&&e&&g.Ec(e,function(){g.l("yt.reactLoaded",!0,void 0)})};
mg.prototype.dispose=function(){g.Bb(this.B);var a=g.m("ytbin.www.pageframe.cancelSetup");a&&a();g.Cb(If);if(a=g.Kf())a.removeEventListener("onReady",Jf),a.removeEventListener("onStateChange",Jf);g.l("yt.timing.ready_",!1,void 0);mg.N.dispose.call(this)};
mg.prototype.disable=function(){mg.N.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfclick",Tf),window.removeEventListener("spfhistory",Uf),window.removeEventListener("spfrequest",Zf),window.removeEventListener("spfpartprocess",cg),window.removeEventListener("spfpartdone",dg),window.removeEventListener("spfprocess",eg),window.removeEventListener("spfdone",hg),window.removeEventListener("spferror",ig),window.removeEventListener("spfreload",jg),window.removeEventListener("spfjsbeforeunload",
ng));window.onload=null;window.onunload=null;window.onerror=null};
g.Yb(new mg);})(_yt_www);
